# Generated by Django 3.0 on 2021-04-29 07:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0003_product'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='im',
            field=models.ImageField(default='home1.png', upload_to='static/images'),
        ),
    ]
